export default {
  "login": "girishgodage",
  "id": 10049525,
  "node_id": "MDQ6VXNlcjEwMDQ5NTI1",
  "avatar_url": "https://avatars.githubusercontent.com/u/10049525?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/girishgodage",
  "html_url": "https://github.com/girishgodage",
  "followers_url": "https://api.github.com/users/girishgodage/followers",
  "following_url": "https://api.github.com/users/girishgodage/following{/other_user}",
  "gists_url": "https://api.github.com/users/girishgodage/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/girishgodage/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/girishgodage/subscriptions",
  "organizations_url": "https://api.github.com/users/girishgodage/orgs",
  "repos_url": "https://api.github.com/users/girishgodage/repos",
  "events_url": "https://api.github.com/users/girishgodage/events{/privacy}",
  "received_events_url": "https://api.github.com/users/girishgodage/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Girish Godage",
  "company": "GGSoftware",
  "blog": "https://girishgodage.in",
  "location": "Juhu-versoa Link Road ,Mumbai ",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "GGodage",
  "public_repos": 227,
  "public_gists": 1,
  "followers": 1,
  "following": 1,
  "created_at": "2014-12-02T16:09:39Z",
  "updated_at": "2021-01-31T08:19:29Z"
  };
